### ISSUE TITLE
Magellanic Stream coordinates

### ISSUE THREAD

**Issue by DanielLenz** [adrn/gala#102]
I've raised this issue earlier in the [core astropy repository](https://github.com/astropy/astropy/issues/7119) and agree that it might be a bit too specific over there, so re-raising here.

I've recently been working with Magellanic Stream coordinates and was wondering if this coordinate set could be implemented here.

The connection to the Galactic coordinate system is presented in [Nidever, Majewski, & Burton (2008)](http://adsabs.harvard.edu/abs/2008ApJ...679..432N). Additionally, there's a brief summary on the transformation [here](http://www.atnf.csiro.au/people/Tobias.Westmeier/tools_coords.php).

I've been using a simple conversion function so far, based on the set of equations in the link above. Do you have any pointers as to how to set this up in the framework that is used for the other coordinate systems implemented in gala (i.e. the rotation matrix)?

**Comment by adrn** [comment]
👋 hi @DanielLenz!

I think we can follow the same sort of transform as FK5 -> Galactic ([as implemented in Astropy](https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/galactic_transforms.py)). That transformation is specified in the same way (as a north pole), so we should be able to construct the rotation matrix in the same way. The one difference is that the longitude = 0 position in the Nidever paper is specified as a position in galactic coordinates, instead of as a single longitude rotation, but I think that's not too much of a complication. 

Let me know if you get stuck!

**Comment by adrn** [comment]
Got distracted by this -- this might be the solution: https://gist.github.com/03271cc028e19de50db6081be15bf622

**Comment by salmanhiro** [comment]
Unrelated to this but I found that there is generalized way to transform into stream coordinate for any streams -- since we have hundreds of streams. I know someone in the future might be looking for this since I spent long time to locate

https://gist.github.com/jobovy/4187b69eb859e0b9bfc26104814bd639
