### ISSUE TITLE
Problems with conversion to galactocentric coordinates

### ISSUE THREAD

**Issue by ckr2** [adrn/gala#110]
Hi, I have never used Python before, but tried your package for conversion to galactocentric coordinates. First you don't offer a Cartesian (heliocentric) to Cartesian (galactocentric) conversion and back. That is a pity because according to the package documentation, you internally change from spherical to Cartesian coordinates, so you can easily overload. Second, I converted from Cartesian to spherical and applied your package to an object within the solar system. The results are way off. Here is a code snippet following your example. 
c = coord.ICRS(ra=23.7597916667 * u.degree,
              dec=8.335 * u.degree,
                distance=1.852935369337427E+08 * u.km)
v_sun = coord.CartesianDifferential([10, 250, 7]*u.km/u.s)
gc_frame = coord.Galactocentric(galcen_distance=8.2*u.kpc,
galcen_v_sun=v_sun,
 z_sun=0*u.pc)
gc2 = c.transform_to(gc_frame)
print(gc2.x, gc2.y, gc2.z)

For gc2.x it prints -2.5302556176703133e+17 km, and if I use gc2.x + galcen_distance, I get -6171355249656000.0 km which is off by over 5 orders of magnitude, since the original heliocentric distance is only 1E+8 km. Floating point error due to adding and subtracting galcen_distance? Am I doing something wrong? Any solution or should I do the conversion manually or write fresh code.

**Comment by smoh** [comment]
This is a while ago, so I'm not sure if you are still interested but if what you're looking for is coordinate transformation, you do not necessarily need this package and can just use [astropy coordinates module](http://docs.astropy.org/en/stable/coordinates/#module-astropy.coordinates).

```python
# go from ICRS cartesian to Galactocentric cartesian and back
icrs_cart = coord.ICRS(x=1*u.kpc, y=2*u.kpc, z=3*u.kpc,
                       v_x=1*u.km/u.s, v_y=2*u.km/u.s, v_z=3*u.km/u.s,
                       representation_type='cartesian',
                       differential_type='cartesian')
galacto = icrs_cart.transform_to(coord.Galactocentric)  # uses default Galacocentric frame parameters
galacto.cartesian.xyz, galacto.v_x, galacto.v_y, galacto.v_z
# (<Quantity [-11.55285355,   1.84539942,   0.141713  ] kpc>,
#  <Quantity 7.84710254 km / s>,
#  <Quantity 234.08539942 km / s>,
#  <Quantity 7.364713 km / s>)
# cartesian velocities can also be accessed as galacto.cartesian.differentials['s'].d_xyz
```

I didn't understand the second issue, but I suppose you may have confusion about how the frames are exactly defined -- more info on frames and coordinate transformation is at the astropy documentation rather than here.

**Comment by ckr2** [comment]
Many thanks for the response. Still very much interested, as my calculations are not quite done. 

I identified the problem. Please see the definition of 

\theta = \asin (z_sun/d_GC) 

in the attached, just above equation 22. The problem is that I want a galactocentric frame whose origin coincides with the physical sun at a given instant of time. Therefore, I put d_GC = 0, which results in division by zero hence a floating point error and NAN in the Python code which has no provision for such a requirement.

The height of the sun above the galactic plane is quite irrelevant to my purposes (which is to solve a dynamical problem). 

Since I also need the inverse transformation etc., I simply wrote some C-code: just a few matrix multiplications. I omit the last bit about positioning the sun above the galactic plane.

However, not sure about the signs of the angles for the rotation matrices used in the astropy package documentation which is too sparse. As you see, I have applied the rotation matrices to the position and velocity vectors, not the axes. Is that what the astropy package intends?

**Comment by adrn** [comment]
Hi @ckr2 (and thanks @smoh!) -- Sorry for missing this issue! 

I don't understand the exact problem you want to solve (I don't see an attachment with equations), but as @smoh has said, the functionality you want is probably either in [astropy](http://docs.astropy.org/en/latest/coordinates/index.html) or [sunpy](http://docs.sunpy.org/en/stable/guide/units-coordinates.html#physical-coordinates-in-sunpy), not in `gala`. 

In Astropy, you might want to take a look at the [Heliocentric ecliptic frame](http://docs.astropy.org/en/latest/api/astropy.coordinates.HeliocentricTrueEcliptic.html#astropy.coordinates.HeliocentricTrueEcliptic) and the [get_sun](http://docs.astropy.org/en/latest/api/astropy.coordinates.get_sun.html#astropy.coordinates.get_sun) function.

In any case, I would recommend first describing your issue in a bit more detail in either the astropy mailing list (https://mail.python.org/mailman/listinfo/astropy) or the Astropy Slack channel (http://joinslack.astropy.org) to get some feedback. There are many solar physicists in those two channels who might be able to help more, otherwise me or one of the other `astropy.coordinates` maintainers can try to help.

Thanks!
