### ISSUE TITLE
Inconsistent circular_velocity output

### ISSUE THREAD

**Issue by balbinot** [adrn/gala#165]
gala.potential.circular_velocity randomly outputs nonsense velocity, despite potential being computed correctly.

See notebook for example:
https://gist.github.com/balbinot/e85fa782a39d02668cdd5ab0b1e8cf56

**Comment by adrn** [comment]
Really sorry for never responding to this...

I realized that this isn't actually a bug per sé, more of a missing error or warning. In the current API, positions always have to be 3D (or match the dimensionality of the potential). All potentials are implemented as 3D cartesian objects right now. So, passing in a number gets promoted into a shape `(1,)` array, but then the code internally (in C) will try to access elements beyond the end of the array. That's why the returned values were erratic and nonsense. Anyways, I just submitted a PR to add an error message to catch cases like this, linked above. Again...really sorry that this fell off of my radar...
